package com.signalscope.store

import android.content.Context

/**
 * Move the position fixes out of `signalscope-map.db` and into the main database, once.
 *
 * ## Why there were two files
 *
 * `map_fix` was written into its own database because, at the time, `Db.kt` was being edited
 * elsewhere and a second file avoided the collision. The cost was structural rather than cosmetic:
 * a bin id and the samples behind it lived in different SQLite files with no transactional
 * relationship, so "mark these bins contributed" and "here is what was in them" could never be
 * made atomic. That blocks the upload bookkeeping the crowdsourced map needs, so the files merge.
 *
 * ## Why this is not part of the migration
 *
 * Room runs a migration inside a transaction and SQLite refuses `ATTACH DATABASE` inside one, so
 * the rows cannot be copied with SQL from within `MIGRATION_3_4`. They are read through the old
 * database's own DAO and inserted through the new one instead, which is slower and completely
 * ordinary. At the reference device's ~8,700 fixes it takes a moment.
 *
 * ## What it guarantees
 *
 * **Nothing is deleted.** The old file is left exactly where it is after a successful import. It
 * costs a few hundred kilobytes and it is the only copy of a position history that cannot be
 * re-collected; deleting it to reclaim that is a bad trade, and a later release can remove it once
 * the merged table has been seen to work.
 *
 * **It runs once, and survives being interrupted.** The marker is written only after the insert
 * returns, so a process killed mid-import re-runs it next start. A re-run is harmless: fixes carry
 * an autogenerated primary key, so re-inserting would duplicate rather than conflict, and the
 * count check below is what actually stops that -- an import into a non-empty table is skipped.
 * The practical consequence is that the import happens on the first start after the update, before
 * any new fix has been written, or not at all.
 */
object MapFixImport {

    private const val PREFS = "map_fix_import"
    private const val KEY_DONE = "done_v1"

    /**
     * @return the number of rows imported, 0 when there was nothing to do, null on failure.
     *
     * Failure is deliberately not fatal and not retried in a loop: the app still works with an
     * empty position history, and a corrupt old file should not prevent the collector starting.
     */
    suspend fun runOnce(ctx: Context): Int? {
        val app = ctx.applicationContext
        val prefs = app.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
        if (prefs.getBoolean(KEY_DONE, false)) return 0

        // No old file means a fresh install: nothing to rescue, and the marker is set so the
        // check is not repeated on every start for the life of the install.
        val legacy = app.getDatabasePath("signalscope-map.db")
        if (!legacy.exists()) {
            prefs.edit().putBoolean(KEY_DONE, true).apply()
            return 0
        }

        return runCatching {
            val dao = Db.get(app).dao()
            // Only ever import into an empty table. This is the real idempotency guard -- the
            // marker only covers the clean path, and an autogenerated key means a second import
            // would duplicate every row rather than be rejected.
            if (dao.fixCount() > 0) {
                prefs.edit().putBoolean(KEY_DONE, true).apply()
                return@runCatching 0
            }

            val old = MapDb.get(app).fixes().all()
            if (old.isEmpty()) {
                prefs.edit().putBoolean(KEY_DONE, true).apply()
                return@runCatching 0
            }

            // Primary keys are dropped rather than carried across: the destination assigns its own,
            // and preserving ids from another database buys nothing when nothing references them.
            dao.insertFixes(old.map { it.copy(id = 0) })

            val moved = dao.fixCount()
            // The marker goes in only once the rows are actually readable at the destination. If
            // this line is never reached the import simply runs again next start.
            prefs.edit().putBoolean(KEY_DONE, true).apply()
            moved
        }.getOrNull()
    }
}
